config/routes.rb
HedytylerApp::Application.routes.draw do
  get '/home_page' => 'pages#new' 
  
  resources :recipe_ingredients

  resources :ingredient_recipes

  resources :add_recipe_id_to_users

  resources :user_recipes

  resources :ingredients

  resources :recipes

  resources :users

end

app/models/user_recipe.rb
class UserRecipe < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
end

app/controllers/user_recipes_controller.rb
class UserRecipesController < ApplicationController
  before_action :set_user_recipe, only: [:show, :edit, :update, :destroy]

  # GET /user_recipes
  # GET /user_recipes.json
  def index
    @user_recipes = UserRecipe.all
  end

  # GET /user_recipes/1
  # GET /user_recipes/1.json
  def show
  end

  # GET /user_recipes/new
  def new
    @user_recipe = UserRecipe.new
  end

  # GET /user_recipes/1/edit
  def edit
  end

  # POST /user_recipes
  # POST /user_recipes.json
  def create
    @user_recipe = UserRecipe.new(user_recipe_params)

    respond_to do |format|
      if @user_recipe.save
        format.html { redirect_to @user_recipe, notice: 'User recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_recipes/1
  # PATCH/PUT /user_recipes/1.json
  def update
    respond_to do |format|
      if @user_recipe.update(user_recipe_params)
        format.html { redirect_to @user_recipe, notice: 'User recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_recipes/1
  # DELETE /user_recipes/1.json
  def destroy
    @user_recipe.destroy
    respond_to do |format|
      format.html { redirect_to user_recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_recipe
      @user_recipe = UserRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_recipe_params
      params.require(:user_recipe).permit(:user_id, :recipe_id)
    end
end

app/helpers/user_recipes_helper.rb
module UserRecipesHelper
end

app/views/user_recipes/_form.html.erb
<%= form_for(@user_recipe) do |f| %>
  <% if @user_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_recipe.errors.count, "error") %> prohibited this user_recipe from being saved:</h2>

      <ul>
      <% @user_recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :username %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= f.collection_select :recipe_id, Recipe.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_recipes/edit.html.erb
<h1>Editing user_recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_recipe %> |
<%= link_to 'Back', user_recipes_path %>

app/views/user_recipes/index.html.erb
<h1>Listing user_recipes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Recipe</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_recipes.each do |user_recipe| %>
      <tr>
        <td><%= user_recipe.user_id %></td>
        <td><%= user_recipe.recipe_id %></td>
        <td><%= link_to 'Show', user_recipe %></td>
        <td><%= link_to 'Edit', edit_user_recipe_path(user_recipe) %></td>
        <td><%= link_to 'Destroy', user_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User recipe', new_user_recipe_path %>

app/views/user_recipes/new.html.erb
<h1>New user_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', user_recipes_path %>

app/views/user_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_recipe.user %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @user_recipe.recipe.name %>
</p>

<%= link_to 'Edit', edit_user_recipe_path(@user_recipe) %> |
<%= link_to 'Back', user_recipes_path %>